FROM python:3.8.7-slim as builder
ARG HUGGINGFACE_TOKEN
ENV HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
COPY docker/requirements.txt /app/

# install
RUN echo "==> Installing ..."  && \
    pip3 install --no-cache-dir --upgrade pip && \
    pip3 install virtualenv && \
    virtualenv -p /usr/local/bin/python /app/env && \
    /app/env/bin/pip install --no-cache-dir --upgrade pip && \
    /app/env/bin/pip install --no-cache-dir -r /app/requirements.txt --extra-index-url https://download.pytorch.org/whl/cpu && \
    rm /app/requirements.txt

# download and quantize model
COPY src/stable-diffusion-quantized/prepare /app/prepare
RUN cd /app/prepare/ && \
    /app/env/bin/python main.py && \
    cd /app && mv prepare/onnx onnx && rm -r prepare

COPY src/stable-diffusion-quantized/model/config.json /app/config.json
COPY src/stable-diffusion-quantized/model/inference.py /app/inference.py

FROM python:3.8.7-slim
COPY --from=builder /app /app
WORKDIR /app

ENTRYPOINT ["python3", "/app/inference.py"]