ARG BASE_IMAGE
FROM ${BASE_IMAGE} as builder

ARG MODEL_ID
ENV MODEL_ID=${MODEL_ID}

# Download and quantized model
RUN echo ${MODEL_ID} && /app/env/bin/python /app/main.py "mock" 1 512 512 ${MODEL_ID}

FROM python:3.8.7-slim
ARG MODEL_ID
ENV MODEL_PATH_ROOT=/app/model/onnx_model
ENV MODEL_ID=${MODEL_ID}
COPY --from=builder /app /app

WORKDIR /app

ENTRYPOINT ["/app/env/bin/python", "/app/main.py"]
